// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmU-hIjVHmkq1kwsB7sbCjPEUhdCo6UM',
    appId: '1:219002192696:web:fd8224e8efcebbe8e7f7cd',
    messagingSenderId: '219002192696',
    projectId: 'wallify-66b29',
    authDomain: 'wallify-66b29.firebaseapp.com',
    storageBucket: 'wallify-66b29.appspot.com',
    measurementId: 'G-MBZ2CKC4HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWyI1MQfKyW3uEobhMCo5I8orYyr6xdxc',
    appId: '1:219002192696:android:3c903e5d17c15d1fe7f7cd',
    messagingSenderId: '219002192696',
    projectId: 'wallify-66b29',
    storageBucket: 'wallify-66b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFVQgSWJM3C4kUczVVLzF1lF_bnFf6FHM',
    appId: '1:219002192696:ios:2cadc425863b2c68e7f7cd',
    messagingSenderId: '219002192696',
    projectId: 'wallify-66b29',
    storageBucket: 'wallify-66b29.appspot.com',
    iosBundleId: 'com.example.wallpaperFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFVQgSWJM3C4kUczVVLzF1lF_bnFf6FHM',
    appId: '1:219002192696:ios:275b61d634bf1048e7f7cd',
    messagingSenderId: '219002192696',
    projectId: 'wallify-66b29',
    storageBucket: 'wallify-66b29.appspot.com',
    iosBundleId: 'com.example.wallpaperFlutter.RunnerTests',
  );
}
